services:
  db:
    image: postgres:15
    container_name: zythologue-db
    restart: always
    environment:
      POSTGRES_USER: zythologue_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist the database data
      - ./db-scripts:/docker-entrypoint-initdb.d # Load the database schema

  api:
    build: . # Dossier dans lequel est votre Dockerfile d'API
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:

  
