version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zythologue-db
    restart: always
    environment:
      POSTGRES_USER: zythologue_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist the database data
      - ./db-scripts:/docker-entrypoint-initdb.d # Load the database schema

api:
      build: ./api
      ports:
        - "3000:3000"
      depends_on:
        - db
      volumes:
        - ./api:/app
      command: ["npm", "start"]
      

volumes:
  postgres_data:
  - ./api:/app
  - /app/node_modules


  # docker-compose up --build -d


# To connect to the PostgreSQL database using DBeaver:
# 1. Open DBeaver and create a new connection.
# 2. Select PostgreSQL as the database type.
# 3. Use the following connection details:
#    - Host: localhost
#    - Port: 5432
#    - Database: zythologue
#    - Username: zythologue_user
#    - Password: securepassword
# 4. Test the connection and save it.
